package Scalabox

/**
  * Created by ladislavlisy on 25.03.16.
  */
object ConfigArticleCode {
  val ARTICLE_UNKNOWN = 0
  val ARTICLE_CONTRACT_EMPL_TERM = 101
  val ARTICLE_POSITION_EMPL_TERM = 110
  val ARTICLE_INCOME_GROSS = 501
  val ARTICLE_INCOME_NETTO = 502
  val ARTICLE_CONTRACT_STAT_TERM = 102
  val ARTICLE_CONTRACT_WORK_TERM = 103
  val ARTICLE_CONTRACT_TASK_TERM = 104
  val ARTICLE_SCHEDULE_WORK = 201
  val ARTICLE_SALARY_BASE = 202
  val ARTICLE_TIMESHEET_SCHEDULE = 251
  val ARTICLE_TIMESHEET_WORKING = 252
  val ARTICLE_TIMESHEET_ABSENCE = 253
  val ARTICLE_TIMEHOURS_WORKING = 254
  val ARTICLE_TIMEHOURS_ABSENCE = 255
  val ARTICLE_HEALTH_INCOME_SUBJECT = 301
  val ARTICLE_SOCIAL_INCOME_SUBJECT = 302
  val ARTICLE_GARANT_INCOME_SUBJECT = 303
  val ARTICLE_HEALTH_INCOME_PARTICIP = 305
  val ARTICLE_SOCIAL_INCOME_PARTICIP = 306
  val ARTICLE_GARANT_INCOME_PARTICIP = 307
  val ARTICLE_HEALTH_BASIS_GENERAL = 311
  val ARTICLE_HEALTH_BASIS_MANDATORY = 312
  val ARTICLE_HEALTH_BASIS_LEGALCAP = 313
  val ARTICLE_SOCIAL_BASIS_GENERAL = 321
  val ARTICLE_SOCIAL_BASIS_PENSION = 322
  val ARTICLE_SOCIAL_BASIS_LEGALCAP = 323
  val ARTICLE_GARANT_BASIS_PENSION = 331
  val ARTICLE_GARANT_BASIS_LEGALCAP = 332
  val ARTICLE_HEALTH_EMPLOYEE_GENERAL = 341
  val ARTICLE_HEALTH_EMPLOYEE_MANDATORY = 342
  val ARTICLE_SOCIAL_EMPLOYEE_GENERAL = 351
  val ARTICLE_SOCIAL_EMPLOYEE_PENSION = 352
  val ARTICLE_GARANT_EMPLOYEE_PENSION = 361
  val ARTICLE_HEALTH_EMPLOYER_GEENRAL = 371
  val ARTICLE_HEALTH_EMPLOYER_MANDATORY = 372
  val ARTICLE_SOCIAL_EMPLOYER_GENERAL = 373
  val ARTICLE_TAXING_INCOME_SUBJECT = 401
  val ARTICLE_TAXING_INCOME_HEALTH = 402
  val ARTICLE_TAXING_INCOME_SOCIAL = 403
  val ARTICLE_TAXING_ADVANCES_INCOME = 411
  val ARTICLE_TAXING_ADVANCES_HEALTH = 412
  val ARTICLE_TAXING_ADVANCES_SOCIAL = 413
  val ARTICLE_TAXING_ADVANCES_BASIS_GENERAL = 414
  val ARTICLE_TAXING_ADVANCES_BASIS_SOLIDARY = 415
  val ARTICLE_TAXING_ADVANCES_GENERAL = 416
  val ARTICLE_TAXING_ADVANCES_SOLIDARY = 417
  val ARTICLE_TAXING_ADVANCES_TOTAL = 418
  val ARTICLE_TAXING_ALLOWANCE_PAYER = 421
  val ARTICLE_TAXING_ALLOWANCE_CHILD = 422
  val ARTICLE_TAXING_ALLOWANCE_DISABILITY = 423
  val ARTICLE_TAXING_ALLOWANCE_STUDYING = 424
  val ARTICLE_TAXING_REBATE_PAYER = 431
  val ARTICLE_TAXING_REBATE_CHILD = 432
  val ARTICLE_TAXING_BONUS_CHILD = 433
  val ARTICLE_TAXING_WITHHOLD_INCOME = 451
  val ARTICLE_TAXING_WITHHOLD_HEALTH = 452
  val ARTICLE_TAXING_WITHHOLD_SOCIAL = 453
  val ARTICLE_TAXING_WITHHOLD_BASIS_GENERAL = 454
  val ARTICLE_TAXING_WITHHOLD_GENERAL = 456
}

